Реорганизация + closeness centrality
sreznick/CodeRankingPro pull request #19
Opened 2021-12-04 23:29 UTC by Anaiya798

Добавила еще один альтернативный метод ранжирования вершин графа - Closeness centrality. В отличие от Katz centrality, он не использует при подсчете бесконечную сумму, таким образом выдает более точное значение ранга. Также провела небольшую реорганизацию кода: сделала интерфейс AnalyzerNode классом, от которого наследуются PageNode, KatzNode, ClosenessNode (эти классы содержат внутри много общих методов => было дублирование кода); вынесла класс Edge в отдельный модуль; убрала лишние импорты.

2021-12-11 21:45 UTC, sreznick requested changes

2021-12-11 21:45 UTC, sreznick commented on examples/hello/ranking.properties
> +process-packages=coderank/hello
Странно, что у вас здесь поменялся путь, а сам пример не поменялся

2021-12-11 21:45 UTC, sreznick commented on gradlew
> +#!/usr/bin/env sh
А вы как-то специально меняли gradlew и gradlew.bat

По идее, они не должны частом меняться.

И что будет, если вы у себя откатите изменения в этом файле и в gradlew.bat и попробуете на старом собрать - он сломается ?

2021-12-11 21:45 UTC, sreznick commented on src/main/java/coderank/impl/analyzer/AnalyzerNode.java
> +    public int index;
лучше private

2021-12-11 21:45 UTC, sreznick commented on src/test/java/coderank/impl/Edge.java
> +    public int right;
private final

2021-12-11 21:45 UTC, sreznick commented on src/test/java/coderank/impl/Edge.java
> +    Edge(int left, int right) {
private - раз уж завели factory

2021-12-12 01:48 UTC, Anaiya798 commented on examples/hello/ranking.properties
> +process-packages=coderank/hello
Да, это я пробовала перемещать папку hello в разные места, пытаясь понять, почему ничего не работает, и данный файл меняла руками. Видимо, при коммите забыла вернуть прежний путь

2021-12-12 02:02 UTC, Anaiya798 commented on gradlew
> +#!/usr/bin/env sh
Это дейсвительно очень странно. Единственное, что я меняла руками в настройках gradle, - это run testing -> using Intellij IDE. Я сделала откат назад, загрузила последние изменения из main в свою ветку anastasiia-changes (сейчас у меня этот файл такой же, как в основном репозитории), и после этого что-то сломалось: при запуске gradlew build из корня проекта вылезает ошибка Task :test FAILED, причем в локальной ветке main с последними изменениями у меня все хорошо: подобных ошибок нет, и само ранжирование запускается, о чем я писала в чате в телеграм

2021-12-12 02:14 UTC, Anaiya798 commented on src/main/java/coderank/impl/analyzer/AnalyzerNode.java
> +    public int index;
Исправила

2021-12-12 02:16 UTC, Anaiya798 commented on src/test/java/coderank/impl/Edge.java
> +    Edge(int left, int right) {
Исправила

2021-12-12 02:20 UTC, Anaiya798 commented on src/test/java/coderank/impl/Edge.java
> +    public int right;
Поскольку класс Edge у нас много где используется, я в дальнейших изменениях вынесла его в отдельный модуль, поэтому модификатор private поставить не получится. Final поставила

2021-12-14 22:50 UTC, sreznick approved these changes

2021-12-14 22:50 UTC, merged